apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 2
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: immuneitdockerregistry.azurecr.io/product-service:1.0
        ports:
          - containerPort: 8080