apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sb-product-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeffreyOomen/product-service-gitops
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sb-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true # override changes made manually
      prune: true # delete resources after self heal
